// This file is auto-generated by scripts/frontend-version-artifacts.sh
// Do not edit manually.
export const VersionInfo = {
  version: `2025.11.10.10000`,
  versionMajor: `2025`,
  versionMinor: `11`,
  versionRelease: `10`,
  versionGlobalRelease: `10000`,
  versionFullNumeric: `2025111010000`,
  versionShort: `2025.11.10`,
  versionShortNumeric: `20251110`,
  buildNumber: `2025-11-16T12:32:06Z`,
  buildComment: `Initial compile with versioning`,
  branch: `main`,
  informationalVersion: `2025.11.10.10000+main.Initial compile with versioning`,
} as const;
