// This file is auto-generated by scripts/frontend-version-artifacts.sh
// Do not edit manually.
export const VersionInfo = {
  version: `2025.11.10.10000`,
  versionMajor: `2025`,
  versionMinor: `11`,
  versionRelease: `10`,
  versionGlobalRelease: `10000`,
  versionFullNumeric: `2025111010000`,
  versionShort: `2025.11.10`,
  versionShortNumeric: `20251110`,
  buildNumber: `2025-11-17T17:40:49Z`,
  buildComment: `Consumes API from backend`,
  branch: `main`,
  informationalVersion: `2025.11.10.10000+main.Consumes API from backend`,
  apiBaseUrl: `https://sab-u-dev-api.chart-finder.app/`,
  companyName: `SoftwareAB`,
  productName: `Chart Finder`,
  companySlug: `softwareab`,
  productSlug: `chartfinder`,
} as const;
