// This file is auto-generated by scripts/frontend-version-artifacts.sh
// Do not edit manually.
export const VersionInfo = {
  version: `2025.11.11.10001`,
  versionMajor: `2025`,
  versionMinor: `11`,
  versionRelease: `11`,
  versionGlobalRelease: `10001`,
  versionFullNumeric: `2025111110001`,
  versionShort: `2025.11.11`,
  versionShortNumeric: `20251111`,
  buildNumber: `2025-11-20T14:33:43Z`,
  buildComment: `Prep for different front-end`,
  branch: `main`,
  informationalVersion: `2025.11.11.10001+main.Prep for different front-end`,
  apiBaseUrl: `https://sab-u-dev-api.chart-finder.app/`,
  companyName: `SoftwareAB`,
  productName: `Chart Finder`,
  companySlug: `softwareab`,
  productSlug: `chartfinder`,
} as const;
