// This file is auto-generated by scripts/frontend-version-artifacts.sh
// Do not edit manually.
class VersionInfo {
  final String version;
  final String versionMajor;
  final String versionMinor;
  final String versionRelease;
  final String versionGlobalRelease;
  final String versionFullNumeric;
  final String versionShort;
  final String versionShortNumeric;
  final String buildNumber;
  final String buildComment;
  final String branch;
  final String informationalVersion;
  final String apiBaseUrl;
  final String companyName;
  final String productName;
  final String companySlug;
  final String productSlug;

  const VersionInfo({
    required this.version,
    required this.versionMajor,
    required this.versionMinor,
    required this.versionRelease,
    required this.versionGlobalRelease,
    required this.versionFullNumeric,
    required this.versionShort,
    required this.versionShortNumeric,
    required this.buildNumber,
    required this.buildComment,
    required this.branch,
    required this.informationalVersion,
    required this.apiBaseUrl,
    required this.companyName,
    required this.productName,
    required this.companySlug,
    required this.productSlug,
  });
}

const versionInfo = VersionInfo(
  version: '2025.11.11.10001',
  versionMajor: '2025',
  versionMinor: '11',
  versionRelease: '11',
  versionGlobalRelease: '10001',
  versionFullNumeric: '2025111110001',
  versionShort: '2025.11.11',
  versionShortNumeric: '20251111',
  buildNumber: '2025-11-20T14:33:43Z',
  buildComment: 'Prep for different front-end',
  branch: 'main',
  informationalVersion: '2025.11.11.10001+main.Prep for different front-end',
  apiBaseUrl: 'https://sab-u-dev-api.chart-finder.app/',
  companyName: 'SoftwareAB',
  productName: 'Chart Finder',
  companySlug: 'softwareab',
  productSlug: 'chartfinder',
);
