#!/bin/bash
# frontend-version-artifacts.sh
# Generate frontend source artifacts (e.g., versionInfo.ts) from frontend/version.json.

# resolve directories
the_frontend_version_artifacts_source="${BASH_SOURCE[0]}"
while [ -h "$the_frontend_version_artifacts_source" ]; do
  the_frontend_version_artifacts_dir="$( cd -P "$( dirname "$the_frontend_version_artifacts_source" )" >/dev/null 2>&1 && pwd )"
  the_frontend_version_artifacts_source="$(readlink "$the_frontend_version_artifacts_source")"
  [[ $the_frontend_version_artifacts_source != /* ]] && the_frontend_version_artifacts_source="$the_frontend_version_artifacts_dir/$the_frontend_version_artifacts_source"
done
the_frontend_version_artifacts_script_dir="$( cd -P "$( dirname "$the_frontend_version_artifacts_source" )" >/dev/null 2>&1 && pwd )"
the_frontend_version_artifacts_root_dir="$( realpath "$the_frontend_version_artifacts_script_dir"/.. )"

source "$the_frontend_version_artifacts_root_dir/scripts/lcl-os-checks.sh" 'source-only' || exit $?
lcl_dot_local_settings_source "$the_frontend_version_artifacts_root_dir" || exit $?
source "$the_frontend_version_artifacts_root_dir/scripts/cf-env-vars.sh" 'source-only' || exit $?

the_frontend_version_artifacts_version_file="$the_frontend_version_artifacts_root_dir/frontend/version.json"
the_frontend_version_artifacts_ts_file="$the_frontend_version_artifacts_root_dir/src/frontend/chart-finder-react/src/versionInfo.ts"

frontend_version_artifacts_log() {
  local i_message="$1"
  printf '[frontend-version-artifacts] %s\n' "$i_message"
}

frontend_version_artifacts_usage() {
  cat <<'USAGE'
Usage: ./scripts/frontend-version-artifacts.sh [command]

Commands:
  run        Generate versionInfo.ts from frontend/version.json (default)
  help       Show this help message
USAGE
}

frontend_version_artifacts_verify_prereqs() {
  if [ ! -f "$the_frontend_version_artifacts_version_file" ]; then
    frontend_version_artifacts_log "ERROR: missing $the_frontend_version_artifacts_version_file"
    return 1
  fi
  local l_ts_dir
  l_ts_dir="$( dirname "$the_frontend_version_artifacts_ts_file" )"
  if ! mkdir -p "$l_ts_dir"; then
    frontend_version_artifacts_log "ERROR: unable to create directory $l_ts_dir"
    return 1
  fi
  return 0
}

frontend_version_artifacts_generate_ts() {
  local l_tmp_file
  l_tmp_file="$(mktemp "${the_frontend_version_artifacts_ts_file}.XXXXXX")" || return 1
  if ! FRONTEND_VERSION_ARTIFACTS_BASE_URI="${CF_LOCAL_BASE_URI:-}" \
    python3 - "$the_frontend_version_artifacts_version_file" "$l_tmp_file" <<'PY'
import json
import os
import sys
import re

version_path, output_path = sys.argv[1], sys.argv[2]
data = json.load(open(version_path, encoding="utf-8"))
base_uri = os.environ.get("FRONTEND_VERSION_ARTIFACTS_BASE_URI", "")

version = data.get("version", "") or ""
parts = version.split(".")
major = parts[0] if len(parts) > 0 else ""
minor = parts[1] if len(parts) > 1 else ""
release = parts[2] if len(parts) > 2 else ""
global_release = parts[3] if len(parts) > 3 else ""

def pad(part: str, width: int) -> str:
    if not part:
        return "".zfill(width)
    digits = "".join(ch for ch in part if ch.isdigit())
    if not digits:
        digits = part
    return digits.zfill(width)

minor_pad = pad(minor, 2) if minor else ""
release_pad = pad(release, 2) if release else ""

version_short_parts = [p for p in (major, minor, release) if p]
version_short = ".".join(version_short_parts)
version_short_numeric = "".join([
    major,
    minor_pad,
    release_pad,
])
version_full_numeric = "".join([
    major,
    minor_pad,
    release_pad,
    global_release or "",
])

company = data.get("company", "")
product = data.get("product", "")

def slugify(value: str) -> str:
    if not value:
        return ""
    lowered = value.lower()
    return re.sub(r"[^a-z0-9]+", "", lowered)

company_slug = slugify(company)
product_slug = slugify(product)

def fmt_value(value: str) -> str:
    return (value or "").replace("\\", "\\\\").replace("`", "\\`")

ts_content = """// This file is auto-generated by scripts/frontend-version-artifacts.sh
// Do not edit manually.
export const VersionInfo = {{
  version: `{version}`,
  versionMajor: `{versionMajor}`,
  versionMinor: `{versionMinor}`,
  versionRelease: `{versionRelease}`,
  versionGlobalRelease: `{versionGlobalRelease}`,
  versionFullNumeric: `{versionFullNumeric}`,
  versionShort: `{versionShort}`,
  versionShortNumeric: `{versionShortNumeric}`,
  buildNumber: `{buildNumber}`,
  buildComment: `{buildComment}`,
  branch: `{branch}`,
  informationalVersion: `{informationalVersion}`,
  apiBaseUrl: `{apiBaseUrl}`,
  companyName: `{companyName}`,
  productName: `{productName}`,
  companySlug: `{companySlug}`,
  productSlug: `{productSlug}`,
}} as const;
""".format(
    version=fmt_value(version),
    versionMajor=fmt_value(major),
    versionMinor=fmt_value(minor),
    versionRelease=fmt_value(release),
    versionGlobalRelease=fmt_value(global_release),
    versionFullNumeric=fmt_value(version_full_numeric),
    versionShort=fmt_value(version_short),
    versionShortNumeric=fmt_value(version_short_numeric),
    buildNumber=fmt_value(data.get("buildNumber", "")),
    buildComment=fmt_value(data.get("comment", "")),
    branch=fmt_value(data.get("branch", "")),
    informationalVersion=fmt_value(data.get("informationalVersion", "")),
    apiBaseUrl=fmt_value(base_uri),
    companyName=fmt_value(company),
    productName=fmt_value(product),
    companySlug=fmt_value(company_slug),
    productSlug=fmt_value(product_slug),
)

with open(output_path, "w", encoding="utf-8") as handle:
    handle.write(ts_content)
PY
  then
    rm -f "$l_tmp_file"
    frontend_version_artifacts_log "ERROR: failed to generate versionInfo.ts content"
    return 1
  fi

  printf '%s\n' "$l_tmp_file"
}

frontend_version_artifacts_write_if_changed() {
  local i_tmp_file="$1"
  if [ ! -f "$the_frontend_version_artifacts_ts_file" ] || ! cmp -s "$i_tmp_file" "$the_frontend_version_artifacts_ts_file"; then
    if ! mv "$i_tmp_file" "$the_frontend_version_artifacts_ts_file"; then
      frontend_version_artifacts_log "ERROR: unable to write $the_frontend_version_artifacts_ts_file"
      rm -f "$i_tmp_file"
      return 1
    fi
    frontend_version_artifacts_log "Updated $the_frontend_version_artifacts_ts_file"
  else
    rm -f "$i_tmp_file"
    frontend_version_artifacts_log "versionInfo.ts unchanged"
  fi
}

frontend_version_artifacts_run() {
  if ! frontend_version_artifacts_verify_prereqs; then
    return 1
  fi
  local l_tmp_file
  if ! l_tmp_file="$(frontend_version_artifacts_generate_ts)"; then
    return 1
  fi
  frontend_version_artifacts_write_if_changed "$l_tmp_file"
}

frontend_version_artifacts_main() {
  local l_command="${1:-run}"
  case "$l_command" in
    run)
      frontend_version_artifacts_run
      ;;
    help|--help|-h)
      frontend_version_artifacts_usage
      ;;
    *)
      frontend_version_artifacts_log "ERROR: unknown command '$l_command'"
      frontend_version_artifacts_usage
      return 1
      ;;
  esac
}

if [ "${1:-}" != "source-only" ]; then
  frontend_version_artifacts_main "$@"
else
  true
fi
